version: "3.2"
services:
  database:
    container_name: user-container
    image: mysql:8.0.22
    volumes:
      - ~/docker/mysql/user/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/user/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/user/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=userdb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3308:3306