INSERT INTO users (mod_date, register_date,username, password, address, name, phone_number, job) values ( NOW(), NOW(), 'alamblot0', 'sV1@95', 'amacnockater0@auda.org.au', 'Abbey', '106-906-8341', 'Graphic Designer');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values (NOW(), NOW(),'ctarbin1', 'rI3|N|', 'ccorradengo1@cam.ac.uk', 'Crawford', '166-127-5418', 'Computer Systems Analyst II');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values (NOW(), NOW(),'deisikowitch2', 'yV6>,5G', 'dsmallacombe2@github.io', 'Duffie', '618-965-4933', 'General Manager');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values (NOW(), NOW(),'arichardes3', 'uA7''"(m', 'astanes3@guardian.co.uk', 'Angel', '204-230-2842', 'Cost Accountant');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values (NOW(), NOW(),'sextill4', 'oQ2\<8{1e', 'soswal4@goo.ne.jp', 'Sonja', '512-524-5012', 'Help Desk Technician');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values (NOW(), NOW(),'wtrask5', 'wF5%O,lW', 'wcromblehome5@woothemes.com', 'Winny', '880-986-6429', 'Business Systems Development Analyst');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values ( NOW(), NOW(),'aabramcik6', 'aX4{A', 'aondricek6@biblegateway.com', 'Aleece', '166-451-7931', 'Business Systems Development Analyst');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values (NOW(), NOW(),'rkintzel7', 'lA7<,Y', 'rhannam7@yahoo.com', 'Richardo', '909-560-7606', 'Account Coordinator');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values (NOW(), NOW(),'kfeldmark8', 'gO8>uM', 'ktagg8@cdc.gov', 'Kynthia', '113-640-2191', 'Desktop Support Technician');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values ( NOW(), NOW(),'afarland9', 'vJ5\X)G#{/', 'ajaimez9@oakley.com', 'Anya', '382-444-5810', 'Chemical Engineer');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values ( NOW(), NOW(),'reeftinga', 'tG0~2X', 'rgrievea@archive.org', 'Rosemary', '126-195-4086', 'Senior Cost Accountant');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values ( NOW(), NOW(),'dmethringhamb', 'pU6,UHX', 'dcullyb@ocn.ne.jp', 'Devlin', '896-121-3333', 'Assistant Media Planner');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values ( NOW(), NOW(),'ltomanc', 'jT9''#R', 'lbrearleyc@stumbleupon.com', 'Lionel', '262-231-2438', 'Software Test Engineer IV');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values ( NOW(), NOW(),'lkollasd', 'eZ0%bp=6LN', 'lseverwrightd@census.gov', 'Lucita', '817-406-3847', 'Registered Nurse');
insert into users (mod_date, register_date,username, password, address, name, phone_number, job) values ( NOW(), NOW(),'dpulvere', 'lI3@bJX', 'dgoblee@cargocollective.com', 'Doy', '637-462-4955', 'Statistician II');

INSERT INTO boards ( mod_date, register_date, board_name, board_type) VALUES (NOW(), NOW(), 'reviews', 'board');
INSERT INTO boards ( mod_date, register_date, board_name, board_type) VALUES (NOW(), NOW(), 'qna', 'board');

INSERT INTO articles (mod_date, register_date, title, content, board_id, user_id)
VALUES
    (NOW(), NOW(), 'Title 1', 'Content 1', 1, 1),
    (NOW(), NOW(), 'Title 2', 'Content 2', 2, 2),
    (NOW(), NOW(), 'Title 3', 'Content 3', 1, 3),
    (NOW(), NOW(), 'Title 4', 'Content 4', 2, 4),
    (NOW(), NOW(), 'Title 5', 'Content 5', 1, 5),
    (NOW(), NOW(), 'Title 6', 'Content 6', 2, 6),
    (NOW(), NOW(), 'Title 7', 'Content 7', 1, 7),
    (NOW(), NOW(), 'Title 8', 'Content 8', 2, 8),
    (NOW(), NOW(), 'Title 9', 'Content 9', 1, 9),
    ( NOW(), NOW(), 'Title 10', 'Content 10', 2, 10),
    ( NOW(), NOW(), 'Title 11', 'Content 11', 1, 11),
    ( NOW(), NOW(), 'Title 12', 'Content 12', 2, 12),
    (NOW(), NOW(), 'Title 13', 'Content 13', 1, 13),
    (NOW(), NOW(), 'Title 14', 'Content 14', 2, 14),
    (NOW(), NOW(), 'Title 15', 'Content 15', 1, 15),
    ( NOW(), NOW(), 'Title 16', 'Content 16', 2, 1),
    (NOW(), NOW(), 'Title 17', 'Content 17', 1, 2),
    (NOW(), NOW(), 'Title 18', 'Content 18', 2, 3),
    (NOW(), NOW(), 'Title 19', 'Content 19', 1, 4),
    (NOW(), NOW(), 'Title 20', 'Content 20', 2, 5),
    (NOW(), NOW(), 'Title 21', 'Content 21', 1, 6),
    (NOW(), NOW(), 'Title 22', 'Content 22', 2, 7),
    (NOW(), NOW(), 'Title 23', 'Content 23', 1, 8),
    (NOW(), NOW(), 'Title 24', 'Content 24', 2, 9),
    (NOW(), NOW(), 'Title 25', 'Content 25', 1, 10),
    (NOW(), NOW(), 'Title 26', 'Content 26', 2, 11),
    (NOW(), NOW(), 'Title 27', 'Content 27', 1, 12),
    (NOW(), NOW(), 'Title 28', 'Content 28', 2, 13),
    (NOW(), NOW(), 'Title 29', 'Content 29', 1, 14),
    (NOW(), NOW(), 'Title 30', 'Content 30', 2, 15),
    (NOW(), NOW(), 'Title 31', 'Content 31', 1, 1),
    (NOW(), NOW(), 'Title 32', 'Content 32', 2, 2),
    (NOW(), NOW(), 'Title 33', 'Content 33', 1, 3),
    (NOW(), NOW(), 'Title 34', 'Content 34', 2, 4),
    (NOW(), NOW(), 'Title 35', 'Content 35', 1, 5),
    (NOW(), NOW(), 'Title 36', 'Content 36', 2, 6),
    (NOW(), NOW(), 'Title 37', 'Content 37', 1, 7),
    (NOW(), NOW(), 'Title 38', 'Content 38', 2, 8),
    (NOW(), NOW(), 'Title 39', 'Content 39', 1, 9),
    (NOW(), NOW(), 'Title 40', 'Content 40', 2, 10),
    (NOW(), NOW(), 'Title 41', 'Content 41', 1, 11),
    (NOW(), NOW(), 'Title 42', 'Content 42', 2, 12),
    (NOW(), NOW(), 'Title 43', 'Content 43', 1, 13),
    (NOW(), NOW(), 'Title 44', 'Content 44', 2, 14),
    (NOW(), NOW(), 'Title 45', 'Content 45', 1, 15),
    (NOW(), NOW(), 'Title 46', 'Content 46', 2, 1),
    (NOW(), NOW(), 'Title 47', 'Content 47', 1, 2),
    (NOW(), NOW(), 'Title 48', 'Content 48', 2, 3),
    (NOW(), NOW(), 'Title 49', 'Content 49', 1, 4),
    (NOW(), NOW(), 'Title 50', 'Content 50', 2, 5),
    (NOW(), NOW(), 'Title 51', 'Content 51', 1, 6),
    (NOW(), NOW(), 'Title 52', 'Content 52', 2, 7),
    (NOW(), NOW(), 'Title 53', 'Content 53', 1, 8),
    (NOW(), NOW(), 'Title 54', 'Content 54', 2, 9),
    (NOW(), NOW(), 'Title 55', 'Content 55', 1, 10),
    (NOW(), NOW(), 'Title 56', 'Content 56', 2, 11),
    (NOW(), NOW(), 'Title 57', 'Content 57', 1, 12),
    (NOW(), NOW(), 'Title 58', 'Content 58', 2, 13),
    (NOW(), NOW(), 'Title 59', 'Content 59', 1, 14),
    (NOW(), NOW(), 'Title 60', 'Content 60', 2, 15),
    (NOW(), NOW(), 'Title 61', 'Content 61', 1, 1),
    (NOW(), NOW(), 'Title 62', 'Content 62', 2, 2),
    (NOW(), NOW(), 'Title 63', 'Content 63', 1, 3),
    (NOW(), NOW(), 'Title 64', 'Content 64', 2, 4),
    (NOW(), NOW(), 'Title 65', 'Content 65', 1, 5),
    (NOW(), NOW(), 'Title 66', 'Content 66', 2, 6),
    (NOW(), NOW(), 'Title 67', 'Content 67', 1, 7),
    (NOW(), NOW(), 'Title 68', 'Content 68', 2, 8),
    (NOW(), NOW(), 'Title 69', 'Content 69', 1, 9),
    (NOW(), NOW(), 'Title 70', 'Content 70', 2, 10),
    (NOW(), NOW(), 'Title 71', 'Content 71', 1, 11),
    (NOW(), NOW(), 'Title 72', 'Content 72', 2, 12),
    (NOW(), NOW(), 'Title 73', 'Content 73', 1, 13),
    (NOW(), NOW(), 'Title 74', 'Content 74', 2, 14),
    (NOW(), NOW(), 'Title 75', 'Content 75', 1, 15),
    (NOW(), NOW(), 'Title 76', 'Content 76', 2, 1),
    (NOW(), NOW(), 'Title 77', 'Content 77', 1, 2),
    (NOW(), NOW(), 'Title 78', 'Content 78', 2, 3),
    (NOW(), NOW(), 'Title 79', 'Content 79', 1, 4),
    (NOW(), NOW(), 'Title 80', 'Content 80', 2, 5),
    (NOW(), NOW(), 'Title 81', 'Content 81', 1, 6),
    (NOW(), NOW(), 'Title 82', 'Content 82', 2, 7),
    (NOW(), NOW(), 'Title 83', 'Content 83', 1, 8),
    (NOW(), NOW(), 'Title 84', 'Content 84', 2, 9),
    (NOW(), NOW(), 'Title 85', 'Content 85', 1, 10),
    (NOW(), NOW(), 'Title 86', 'Content 86', 2, 11),
    (NOW(), NOW(), 'Title 87', 'Content 87', 1, 12),
    (NOW(), NOW(), 'Title 88', 'Content 88', 2, 13),
    (NOW(), NOW(), 'Title 89', 'Content 89', 1, 14),
    (NOW(), NOW(), 'Title 90', 'Content 90', 2, 15),
    (NOW(), NOW(), 'Title 91', 'Content 91', 1, 1),
    (NOW(), NOW(), 'Title 92', 'Content 92', 2, 2),
    (NOW(), NOW(), 'Title 93', 'Content 93', 1, 3),
    (NOW(), NOW(), 'Title 94', 'Content 94', 2, 4),
    (NOW(), NOW(), 'Title 95', 'Content 95', 1, 5),
    (NOW(), NOW(), 'Title 96', 'Content 96', 2, 6),
    (NOW(), NOW(), 'Title 97', 'Content 97', 1, 7),
    (NOW(), NOW(), 'Title 98', 'Content 98', 2, 8),
    (NOW(), NOW(), 'Title 99', 'Content 99', 1, 9),
    (NOW(), NOW(), 'Title 100', 'Content 100', 2, 10),
    (NOW(), NOW(), 'Title 101', 'Content 101', 1, 11),
    (NOW(), NOW(), 'Title 102', 'Content 102', 2, 12),
    (NOW(), NOW(), 'Title 103', 'Content 103', 1, 13),
    (NOW(), NOW(), 'Title 104', 'Content 104', 2, 14),
    (NOW(), NOW(), 'Title 105', 'Content 105', 1, 15),
    (NOW(), NOW(), 'Title 106', 'Content 106', 2, 1),
    (NOW(), NOW(), 'Title 107', 'Content 107', 1, 2),
    (NOW(), NOW(), 'Title 108', 'Content 108', 2, 3),
    (NOW(), NOW(), 'Title 109', 'Content 109', 1, 4),
    (NOW(), NOW(), 'Title 110', 'Content 110', 2, 5),
    (NOW(), NOW(), 'Title 111', 'Content 111', 1, 6),
    (NOW(), NOW(), 'Title 112', 'Content 112', 2, 7),
    (NOW(), NOW(), 'Title 113', 'Content 113', 1, 8),
    (NOW(), NOW(), 'Title 114', 'Content 114', 2, 9),
    (NOW(), NOW(), 'Title 115', 'Content 115', 1, 10),
    (NOW(), NOW(), 'Title 116', 'Content 116', 2, 11),
    (NOW(), NOW(), 'Title 117', 'Content 117', 1, 12),
    (NOW(), NOW(), 'Title 118', 'Content 118', 2, 13),
    (NOW(), NOW(), 'Title 119', 'Content 119', 1, 14),
    (NOW(), NOW(), 'Title 120', 'Content 120', 2, 15);